import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  searchArchive,
  isValidProjectDir,
  isValidTranscriptPath,
  type FindChatRunner,
} from '../src/findchat.ts';
import { CLAUDE_PROJECTS_DIR } from '../src/paths.ts';

// A real file on disk: searchArchive drops hits whose transcript no longer exists,
// so fixtures need a path that actually resolves.
const TMP = fs.mkdtempSync(path.join(os.tmpdir(), 'loom-fc-hits-'));
const LIVE_JSONL = path.join(TMP, 'sess-1.jsonl');
fs.writeFileSync(LIVE_JSONL, '{}\n');
const GONE_JSONL = path.join(TMP, 'deleted.jsonl'); // deliberately never created

function hit(over: Record<string, unknown> = {}) {
  return {
    session_id: 'sess-1',
    project_dir: '/Users/w/dev/proj',
    jsonl_path: LIVE_JSONL,
    started_at: 1000,
    ended_at: 2000,
    message_count: 42,
    title: 'dropdown a11y refactor',
    snippet: 'fixing the [dropdown] size regression',
    score: 3.2,
    ...over,
  };
}

// Stand in for find-chat's stdout payload.
function stdout(results: unknown[], extra: Record<string, unknown> = {}) {
  return JSON.stringify({ query: 'q', count: results.length, excluded: [], results, ...extra });
}

describe('searchArchive', () => {
  it('parses find-chat stdout into hits', async () => {
    const runner: FindChatRunner = async () => stdout([hit(), hit({ session_id: 'sess-2' })]);
    const r = await searchArchive('dropdown', [], runner);
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.results.map((x) => x.session_id)).toEqual(['sess-1', 'sess-2']);
    expect(r.results[0].jsonl_path).toContain('sess-1.jsonl');
    expect(r.results[0].message_count).toBe(42);
  });

  it('strips slash-command caveat boilerplate from the heading text', async () => {
    // ~17% of indexed chats open with this block; without stripping it becomes the
    // whole visible heading of an archive card.
    const raw =
      '<local-command-caveat>Caveat: The messages below were generated by the user ' +
      'while running local commands. DO NOT respond to these messages.</local-command-caveat>\n' +
      '<command-name>/clear</command-name>\n<command-message>clear</command-message>\n' +
      '<command-args></command-args>\ncan you give me the url for step c';
    const runner: FindChatRunner = async () => stdout([hit({ title: '', snippet: raw })]);
    const r = await searchArchive('url', [], runner);
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.results[0].snippet).toBe('/clear can you give me the url for step c');
    expect(r.results[0].snippet).not.toContain('Caveat');
  });

  it('strips a caveat block truncated mid-way by an FTS snippet window', async () => {
    // snippet() cuts at N tokens, so the closing tag is often missing. Without the
    // open-ended arm, only the tag is removed and the disclaimer prose survives as
    // the heading. find-chat now cleans at index time; this is the belt-and-braces.
    const runner: FindChatRunner = async () =>
      stdout([
        hit({
          title: '',
          snippet: '<local-command-caveat>Caveat: The messages below were generated by the user…',
        }),
      ]);
    const r = await searchArchive('x', [], runner);
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.results[0].snippet).not.toContain('Caveat');
  });

  it('leaves ordinary text untouched, including find-chat match markers', async () => {
    const runner: FindChatRunner = async () =>
      stdout([hit({ title: '', snippet: 'fixing the [dropdown] size regression' })]);
    const r = await searchArchive('dropdown', [], runner);
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.results[0].snippet).toBe('fixing the [dropdown] size regression');
  });

  it('drops hits whose transcript has been deleted', async () => {
    // find-chat's index keeps rows for files that no longer exist (~half of it in
    // practice). Those chats can't be opened or resumed, so they must not surface.
    const runner: FindChatRunner = async () =>
      stdout([hit(), hit({ session_id: 'sess-gone', jsonl_path: GONE_JSONL })]);
    const r = await searchArchive('dropdown', [], runner);
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.results.map((x) => x.session_id)).toEqual(['sess-1']);
  });

  it('passes one --exclude per session id, with the query last as a single arg', async () => {
    let seen: string[] = [];
    const runner: FindChatRunner = async (args) => {
      seen = args;
      return stdout([]);
    };
    await searchArchive('dropdown bug', ['a1', 'b2'], runner);
    expect(seen).toEqual(['--exclude', 'a1', '--exclude', 'b2', 'dropdown bug']);
  });

  it('short-circuits an empty query without invoking find-chat', async () => {
    let called = false;
    const runner: FindChatRunner = async () => {
      called = true;
      return stdout([hit()]);
    };
    const r = await searchArchive('   ', [], runner);
    expect(r).toEqual({ ok: true, results: [] });
    expect(called).toBe(false);
  });

  it('reports a missing find-chat rather than throwing', async () => {
    const runner: FindChatRunner = async () => {
      const e = new Error('spawn ENOENT') as NodeJS.ErrnoException;
      e.code = 'ENOENT';
      throw e;
    };
    expect(await searchArchive('x', [], runner)).toEqual({
      ok: false,
      detail: 'find-chat not installed',
    });
  });

  it('reports a timeout rather than throwing', async () => {
    const runner: FindChatRunner = async () => {
      const e = new Error('timeout') as Error & { killed: boolean };
      e.killed = true;
      throw e;
    };
    expect(await searchArchive('x', [], runner)).toEqual({ ok: false, detail: 'search timed out' });
  });

  it('reports unparseable stdout rather than throwing', async () => {
    const runner: FindChatRunner = async () => 'not json at all';
    const r = await searchArchive('x', [], runner);
    expect(r.ok).toBe(false);
    if (r.ok) return;
    expect(r.detail).toMatch(/unparseable/);
  });

  it('reports an unexpected payload shape', async () => {
    const runner: FindChatRunner = async () => JSON.stringify({ nope: true });
    const r = await searchArchive('x', [], runner);
    expect(r.ok).toBe(false);
    if (r.ok) return;
    expect(r.detail).toMatch(/unexpected shape/);
  });

  it('drops malformed entries but keeps well-formed ones', async () => {
    const runner: FindChatRunner = async () => stdout([hit(), { bogus: 1 }, null]);
    const r = await searchArchive('x', [], runner);
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.results).toHaveLength(1);
  });
});

describe('isValidProjectDir', () => {
  it('accepts an existing absolute directory', () => {
    expect(isValidProjectDir(os.tmpdir())).toBe(true);
  });

  it('rejects relative paths, non-existent paths, and files', () => {
    const f = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'loom-fc-')), 'a.txt');
    fs.writeFileSync(f, 'x');
    expect(isValidProjectDir('relative/dir')).toBe(false);
    expect(isValidProjectDir('/definitely/not/here/at/all')).toBe(false);
    expect(isValidProjectDir(f)).toBe(false); // a file is not a project dir
    expect(isValidProjectDir('')).toBe(false);
  });
});

describe('isValidTranscriptPath', () => {
  const dir = path.join(CLAUDE_PROJECTS_DIR, '-loom-findchat-test');

  it('accepts an existing .jsonl inside ~/.claude/projects', () => {
    fs.mkdirSync(dir, { recursive: true });
    const p = path.join(dir, 'sess.jsonl');
    fs.writeFileSync(p, '{}\n');
    try {
      expect(isValidTranscriptPath(p)).toBe(true);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('rejects paths outside ~/.claude/projects, traversal, and non-.jsonl', () => {
    fs.mkdirSync(dir, { recursive: true });
    const notJsonl = path.join(dir, 'sess.txt');
    fs.writeFileSync(notJsonl, 'x');
    try {
      expect(isValidTranscriptPath('/etc/passwd')).toBe(false);
      expect(isValidTranscriptPath(notJsonl)).toBe(false);
      // traversal that lands outside the projects root
      expect(isValidTranscriptPath(path.join(CLAUDE_PROJECTS_DIR, '..', '..', 'evil.jsonl'))).toBe(
        false,
      );
      expect(isValidTranscriptPath('')).toBe(false);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});
